# Generated by Django 6.1.1 on 2026-09-27 11:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('pedidos', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaPorCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('importe_cobrado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_cobro', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COBRADO', 'Cobrado'), ('PARCIAL', 'Cobro parcial'), ('VENCIDO', 'Vencido')], default='PENDIENTE', max_length=20)),
                ('numero_factura', models.CharField(blank=True, max_length=50)),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_cobrar', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Cuenta por cobrar',
                'verbose_name_plural': 'Cuentas por cobrar',
                'ordering': ['fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='CobroCuentaPorCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('metodo', models.CharField(blank=True, max_length=50)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to='finanzas.cuentaporcobrar')),
            ],
            options={
                'verbose_name': 'Cobro de cuenta por cobrar',
                'verbose_name_plural': 'Cobros de cuentas por cobrar',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CuentaPorPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('PROVEEDOR', 'Proveedor'), ('SS', 'Seguridad Social'), ('HACIENDA', 'Hacienda / AEAT'), ('AUTONOMO', 'Cuota Autónomo'), ('NOMINA', 'Nómina empleado'), ('ALQUILER', 'Alquiler'), ('SUMINISTRO', 'Suministros (luz, agua...)'), ('PRESTAMO', 'Préstamo'), ('IMPUESTO', 'Impuestos'), ('SERVICIO', 'Servicios profesionales'), ('OTRO', 'Otro')], default='PROVEEDOR', max_length=20)),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('importe_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('PARCIAL', 'Pago parcial'), ('VENCIDO', 'Vencido')], default='PENDIENTE', max_length=20)),
                ('periodicidad', models.CharField(choices=[('UNICO', 'Pago único'), ('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('ANUAL', 'Anual')], default='UNICO', max_length=20)),
                ('numero_factura', models.CharField(blank=True, max_length=50)),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_pagar', to='proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Cuenta por pagar',
                'verbose_name_plural': 'Cuentas por pagar',
                'ordering': ['fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso (venta)'), ('GASTO', 'Gasto (compra)')], max_length=10)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('COMERCIO_MATERIALES', 'Comercio de Materiales'), ('SERVICIOS_PROFESIONALES', 'Servicios Profesionales'), ('SUMINISTROS', 'Suministros'), ('RENTA_PARKING', 'Renta Parking'), ('TRANSPORTE', 'Transporte'), ('MANTENIMIENTO', 'Mantenimiento'), ('IMPUESTOS', 'Impuestos'), ('OTROS', 'Otros')], default='OTROS', max_length=50)),
                ('base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=21, max_digits=5)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('PARCIAL', 'Pago parcial'), ('VENCIDO', 'Vencido')], default='PENDIENTE', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='clientes.cliente')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='pedidos.pedido')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PagoCuentaPorPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('metodo', models.CharField(blank=True, max_length=50)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='finanzas.cuentaporpagar')),
            ],
            options={
                'verbose_name': 'Pago de cuenta por pagar',
                'verbose_name_plural': 'Pagos de cuentas por pagar',
                'ordering': ['-fecha'],
            },
        ),
    ]
