# Generated by Django 5.2.6 on 2026-10-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrocuentaporcobrar',
            name='archivo_factura',
            field=models.FileField(blank=True, null=True, upload_to='facturas_proveedor/%Y/%m/', verbose_name='Factura del proveedor (PDF)'),
        ),
        migrations.AddField(
            model_name='factura',
            name='archivo_factura',
            field=models.FileField(blank=True, null=True, upload_to='facturas_proveedor/%Y/%m/', verbose_name='Factura del proveedor (PDF)'),
        ),
        migrations.AddField(
            model_name='pagocuentaporpagar',
            name='archivo_factura',
            field=models.FileField(blank=True, null=True, upload_to='facturas_proveedor/%Y/%m/', verbose_name='Factura del proveedor (PDF)'),
        ),
    ]
