# Generated by Django 5.2.6 on 2026-10-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_cobrocuentaporcobrar_archivo_factura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaporpagar',
            name='archivo_factura',
            field=models.FileField(blank=True, null=True, upload_to='facturas_proveedor/%Y/%m/', verbose_name='Factura del proveedor (PDF)'),
        ),
    ]
