# Generated by Django 5.2.6 on 2026-10-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_cuentaporpagar_archivo_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='archivo_factura',
        ),
        migrations.AddField(
            model_name='factura',
            name='archivo_justificante',
            field=models.FileField(blank=True, null=True, upload_to='justificantes_pago/%Y/%m/', verbose_name='Justificante del pago (PDF/imagen)'),
        ),
    ]
