# Generated by Django 5.2.6 on 2026-10-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_remove_cobrocuentaporcobrar_archivo_factura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagocuentaporpagar',
            name='archivo_factura',
        ),
        migrations.AddField(
            model_name='pagocuentaporpagar',
            name='archivo_justificante',
            field=models.FileField(blank=True, null=True, upload_to='justificantes_pago/%Y/%m/', verbose_name='Justificante del pago (PDF/imagen)'),
        ),
        migrations.AlterField(
            model_name='cobrocuentaporcobrar',
            name='archivo_justificante',
            field=models.FileField(blank=True, null=True, upload_to='justificantes_cobro/%Y/%m/', verbose_name='Justificante del cobro (PDF/imagen)'),
        ),
    ]
