# Generated by Django 5.2.6 on 2026-10-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_remove_pagocuentaporpagar_archivo_factura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COBRADO', 'Cobrado'), ('PARCIAL', 'Cobro parcial'), ('VENCIDO', 'Vencido'), ('ANULADO', 'Anulada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='cuentaporpagar',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('PARCIAL', 'Pago parcial'), ('VENCIDO', 'Vencido'), ('ANULADO', 'Anulada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado_pago',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('PARCIAL', 'Pago parcial'), ('VENCIDO', 'Vencido'), ('ANULADO', 'Anulada')], default='PENDIENTE', max_length=20),
        ),
    ]
