# Generated by Django 6.1.1 on 2026-09-27 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('unidad', models.CharField(choices=[('KG', 'Kilogramos'), ('TN', 'Toneladas'), ('UD', 'Unidades')], default='TN', max_length=5)),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descripcion', models.TextField(blank=True)),
                ('stock_minimo_critico', models.DecimalField(decimal_places=2, default=100, max_digits=12, verbose_name='Stock mínimo crítico (tn)')),
                ('stock_minimo_bajo', models.DecimalField(decimal_places=2, default=500, max_digits=12, verbose_name='Stock mínimo bajo (tn)')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['tipo__nombre', 'subgrupo__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='SubgrupoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Subgrupo de material',
                'verbose_name_plural': 'Subgrupos de material',
                'ordering': ['tipo__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de material',
                'verbose_name_plural': 'Tipos de material',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventario.material')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventario',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='subgrupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materiales', to='inventario.subgrupomaterial'),
        ),
        migrations.AddField(
            model_name='subgrupomaterial',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgrupos', to='inventario.tipomaterial'),
        ),
        migrations.AddField(
            model_name='material',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiales', to='inventario.tipomaterial'),
        ),
        migrations.AlterUniqueTogether(
            name='subgrupomaterial',
            unique_together={('tipo', 'nombre')},
        ),
    ]
