server {
    listen 80;
    server_name 5.188.183.166 erp-star-recycling.com www.erp-star-recycling.com;

    location = /favicon.ico { access_log off; log_not_found off; }

    location /static/ {
        alias /var/www/erp-reciclaje/staticfiles/;
    }

    location /media/ {
        alias /var/www/erp-reciclaje/media/;
    }

    location / {
        proxy_pass http://unix:/var/www/erp-reciclaje/erp.sock;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}