# Generated by Django 6.1.1 on 2026-09-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='STAR MEDI RECYCLING SL', max_length=200)),
                ('nif', models.CharField(default='B12345678', max_length=20)),
                ('direccion', models.CharField(default='Calle Ejemplo, 123', max_length=300)),
                ('ciudad', models.CharField(default='Barcelona', max_length=100)),
                ('codigo_postal', models.CharField(default='08001', max_length=10)),
                ('provincia', models.CharField(default='Barcelona', max_length=100)),
                ('pais', models.CharField(default='España', max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('web', models.URLField(blank=True)),
                ('iban', models.CharField(blank=True, default='ES21 2101 8249 1592 0201 7568', max_length=50)),
                ('banco', models.CharField(blank=True, default='BBVA', max_length=100)),
                ('swift', models.CharField(blank=True, default='BBVAESMMXXX', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('texto_pie', models.TextField(blank=True, default='VAT EXEMPT ACCORDING TO ARTICLE 21 LAW 37/1992')),
            ],
            options={
                'verbose_name': 'Datos de la Empresa',
                'verbose_name_plural': 'Datos de la Empresa',
            },
        ),
    ]
