# Generated by Django 6.1.1 on 2026-09-27 11:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('inventario', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('porcentaje_anticipo', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('dias_antes_llegada', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Condición de pago',
                'verbose_name_plural': 'Condiciones de pago',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(blank=True, max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('VENTA_MAT', 'Venta de Material'), ('COMPRA_MAT', 'Compra de Material'), ('PREVISION', 'Previsión'), ('CONSULTA', 'Consulta'), ('TRADE', 'Trade'), ('MAQUILA', 'Maquila')], default='VENTA_MAT', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('incoterm', models.CharField(blank=True, choices=[('', '-- Sin incoterm --'), ('EXW', 'EXW - En fábrica'), ('FOB', 'FOB - Libre a bordo'), ('CIF', 'CIF - Coste, seguro y flete'), ('CFR', 'CFR - Coste y flete'), ('DAP', 'DAP - Entrega en destino'), ('DDP', 'DDP - Entrega con derechos pagados')], default='', max_length=10, verbose_name='Incoterm')),
                ('notas', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='clientes.cliente')),
                ('pedido_origen', models.ForeignKey(blank=True, limit_choices_to={'tipo__in': ['COMPRA_MAT']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_venta', to='pedidos.pedido', verbose_name='Pedido de compra origen')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transporte', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.material')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Detalle de pedido',
                'verbose_name_plural': 'Detalles de pedidos',
            },
        ),
        migrations.CreateModel(
            name='PedidoInternacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambito', models.CharField(choices=[('NACIONAL', 'Nacional'), ('INTERNACIONAL', 'Internacional')], default='INTERNACIONAL', max_length=20)),
                ('provincia_destino', models.CharField(blank=True, help_text='Solo para nacional', max_length=100)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto / En preparación'), ('EN_TRANSITO', 'En tránsito marítimo'), ('EN_DESTINO', 'En destino / Aduana'), ('ENTREGADO', 'Entregado al cliente'), ('CERRADO', 'Cerrado y cobrado')], default='ABIERTO', max_length=20)),
                ('incoterm', models.CharField(choices=[('EXW', 'EXW - En fábrica'), ('FOB', 'FOB - Libre a bordo'), ('CIF', 'CIF - Coste, seguro y flete'), ('CFR', 'CFR - Coste y flete'), ('DAP', 'DAP - Entrega en destino'), ('DDP', 'DDP - Entrega con derechos pagados')], default='CIF', max_length=10)),
                ('numero_contenedor', models.CharField(blank=True, max_length=50)),
                ('numero_precinto', models.CharField(blank=True, max_length=50)),
                ('naviera', models.CharField(blank=True, max_length=100)),
                ('numero_bl', models.CharField(blank=True, max_length=50, verbose_name='Nº Bill of Lading')),
                ('buque', models.CharField(blank=True, max_length=100)),
                ('fecha_carga', models.DateField(blank=True, null=True)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('fecha_eta', models.DateField(blank=True, null=True, verbose_name='Fecha estimada de llegada (ETA)')),
                ('fecha_entrega_real', models.DateField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor total (€)')),
                ('coste_flete', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Coste flete (€)')),
                ('peso_total_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Peso total (tn)')),
                ('puerto_origen', models.CharField(blank=True, default='Barcelona', max_length=100)),
                ('puerto_destino', models.CharField(blank=True, max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('condicion_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.condicionpago')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internacional', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Pedido internacional',
                'verbose_name_plural': 'Pedidos internacionales',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PagoInternacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ANTICIPO', 'Anticipo'), ('SALDO', 'Saldo final'), ('PARCIAL', 'Pago parcial'), ('OTRO', 'Otro')], default='ANTICIPO', max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha', models.DateField()),
                ('metodo', models.CharField(blank=True, help_text='Transferencia, LC, etc.', max_length=50)),
                ('referencia', models.CharField(blank=True, help_text='Nº referencia bancaria', max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('pedido_internacional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='pedidos.pedidointernacional')),
            ],
            options={
                'verbose_name': 'Pago internacional',
                'verbose_name_plural': 'Pagos internacionales',
                'ordering': ['-fecha'],
            },
        ),
    ]
