# Generated by Django 6.1.1 on 2026-10-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PREVISION', 'Previsión (sin material)'), ('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PREVISION', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo',
            field=models.CharField(choices=[('VENTA_MAT', 'Venta de Material'), ('COMPRA_MAT', 'Compra de Material'), ('MAQUILA', 'Maquila')], default='VENTA_MAT', max_length=20),
        ),
    ]
