# Generated by Django 5.2.6 on 2026-10-08 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedido_estado_alter_pedido_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrigenVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_tn', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad (tn) de este origen')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('pedido_compra', models.ForeignKey(limit_choices_to={'tipo__in': ['COMPRA_MAT', 'MAQUILA']}, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_asociadas', to='pedidos.pedido')),
                ('pedido_venta', models.ForeignKey(limit_choices_to={'tipo': 'VENTA_MAT'}, on_delete=django.db.models.deletion.CASCADE, related_name='origenes_venta', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Origen de venta',
                'verbose_name_plural': 'Orígenes de venta',
                'ordering': ['-fecha_asignacion'],
            },
        ),
    ]
