# Generated by Django 6.1.1 on 2026-10-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo_nima',
            field=models.CharField(blank=True, max_length=50, verbose_name='Código NIMA'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nif',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero_gestor',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nº Gestor de Residuos'),
        ),
    ]
