# Generated by Django 5.2.6 on 2026-10-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_codigo_nima_cliente_nif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
