# Generated by Django 6.1.1 on 2026-09-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nif', models.CharField(blank=True, max_length=20)),
                ('pais', models.CharField(default='España', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('tipo', models.CharField(choices=[('MATERIAL', 'Material'), ('SERVICIO', 'Servicio'), ('SUMINISTRO', 'Suministro'), ('IMPUESTO', 'Impuesto / Administración'), ('OTRO', 'Otro')], default='MATERIAL', max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20)),
                ('iban', models.CharField(blank=True, max_length=50)),
                ('notas', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
    ]
